default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: paymail_development

test:
  <<: *default
  database: paymail_test

production:
  url: <%= ENV['DATABASE_URL'] %>
